version: '3.9'
services:
  web:
    build: .
    container_name: django_app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - RUN_MIGRATIONS=true
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=your_secure_password
      - DATABASE_URL=sqlite:///data/db.sqlite3
  
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    environment:
      - STRIPE_API_KEY=sk_test_51PfA0tRt3PcgmiF6E8mEDNQrL0UmX8hDNGesoT1xXQ9MWwOrjIibcL2DhQMCjzrAEfLJrCB8AbbQSdrUdLrqdjQS00GcZ8ptR4
      - STRIPE_DEVICE_NAME=docker-container
    command: "listen --forward-to web:8000/webhooks/stripe/"