version: '3.9'

services:
  db:
    image: mysql:8.0  # Use a specific MySQL version
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password
      MYSQL_DATABASE: court_management_system  # Database to auto-create
      MYSQL_USER: user  # Custom MySQL user
      MYSQL_PASSWORD: password  # Password for the user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persistent data storage
      - ./mysql-init:/docker-entrypoint-initdb.d  # Run custom scripts at startup

  web:
    build: .
    container_name: django_app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: court_management_system
      DATABASE_USER: user
      DATABASE_PASSWORD: password

volumes:
  db_data:
