# Generated by Django 5.0.6 on 2024-07-17 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_user_venue_itemcourt_itemtime_itemorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='item',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcourt',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcourt',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorder',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemtime',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtime',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
