# Generated by Django 5.0.6 on 2024-10-02 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_and_court',
        ),
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_role',
            field=models.CharField(max_length=50),
        ),
    ]
