# Generated by Django 5.0.6 on 2024-10-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_booking_time_and_court_booking_court_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
