# Generated by Django 5.0.6 on 2024-10-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
